name: GMode
main: org.pegasus.minecraft.gmode.GMode
version: 0.1
author: Pegasus
description: Allows users to select their own GameMode, PermissionsEx compatible

commands:
   mode:
      description: Select GameMode
      usage: /<command> (creative|survival)